### ISSUE TITLE
[chore] Use bash variables in readmes

### ISSUE THREAD

**Issue by laeckerv** [formigas/formigas-flutter-bricks#102]
It would be beneficial if we use actually variables instead of placeholders
 
Before:

`mason add formigas_custom_theme --git-url git@github.com:formigas/formigas-flutter-bricks.git --git-path formigas_custom_theme --git-ref {VERSION}`

After
`mason add formigas_custom_theme --git-url git@github.com:formigas/formigas-flutter-bricks.git --git-path formigas_custom_theme --git-ref ${VERSION}`

**Comment by Peetee06** [comment]
Closing, because these instructions were removed, as they are redundant with the instructions on BrickHub. E.g. for the [GoRouter brick](https://brickhub.dev/bricks/formigas_go_router#usage).
